extends: site.yaml

mode: production
media_url: /~opo140030/media
base_url: /~opo140030
deploy_root: deploy_production
repository_url: https://github.com/SeRViCE-Lab/website

publisher:
    ssh:
        type: hyde.ext.publishers.ssh.SSH
        username: lakehanne
        server: ecs.utdallas.edu
        target: /home/eng/o/opo140030/public_html